# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ff2c68c4128f87502f27c91d75f8f51"
name = "Chat With Ads"
handle = "chat-with-ads"
application_url = "https://this-writer-clock-ecological.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,read_analytics"

[auth]
redirect_urls = ["https://this-writer-clock-ecological.trycloudflare.com/auth/callback", "https://this-writer-clock-ecological.trycloudflare.com/auth/shopify/callback", "https://this-writer-clock-ecological.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
