# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ff2c68c4128f87502f27c91d75f8f51"
name = "Chat With Ads"
handle = "chat-with-ads"
application_url = "https://advice-annotated-taylor-sequences.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,read_analytics"

[auth]
redirect_urls = ["https://advice-annotated-taylor-sequences.trycloudflare.com/auth/callback", "https://advice-annotated-taylor-sequences.trycloudflare.com/auth/shopify/callback", "https://advice-annotated-taylor-sequences.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
